### ISSUE TITLE
Colours do not come out as shown in tutorial

### ISSUE THREAD

**Issue by ralphrmartin** [DangerousPrototypes/BusPirate5-firmware#36]
Using a an ANSI colour compatible terminal with VT100, I get some colour, but nothing like that shown on the tutorial pages

**Comment by ralphrmartin** [comment]
![Screenshot 2024-04-24 at 21 25 12](https://github.com/DangerousPrototypes/BusPirate5-firmware/assets/5293194/17d562e6-0f15-4a42-ad23-e94e81edc787)

**Comment by MrAureliusR** [comment]
This is almost certainly your terminal enforcing a theme of some sort. I had the same issue with minicom inside of kitty, because I have a specific theme chosen for kitty. The only serial terminal I've tried so far that looked correct was Tabby, though I may try some other basic ones like xterm or rxvt etc.

**Comment by lersi** [comment]
Hello, is this issue still relevant?
I remember patching this issue by adding the option to change the color to ANSI-256

**Comment by MrAureliusR** [comment]
Trying to test the latest firmware to see if it's fixed, but the build fails. Going to open an issue.

**Comment by ralphrmartin** [comment]
I switched to using a different terminal, which works fine.
